// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizeService.Application;
using QuizeService.Domain.Questions;

#nullable disable

namespace QuizeService.Application.Migrations
{
    [DbContext(typeof(QuizeServiceDbContext))]
    [Migration("20251020191448_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizeService.Domain.Questions.MatchQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid?>("TestId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_match_questions");

                    b.HasIndex("TestId");

                    b.HasIndex("TestId1");

                    b.ToTable("match_questions", (string)null);
                });

            modelBuilder.Entity("QuizeService.Domain.Questions.SingleChoiceQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<List<int>>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("correct_answers");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<List<Pair>>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid?>("TestId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_single_choice_questions");

                    b.HasIndex("TestId");

                    b.HasIndex("TestId1");

                    b.ToTable("single_choice_questions", (string)null);
                });

            modelBuilder.Entity("QuizeService.Domain.Questions.TextInputQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("case_sensitive");

                    b.PrimitiveCollection<List<string>>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("correct_answers");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("pk_text_input_questions");

                    b.HasIndex("TestId");

                    b.ToTable("text_input_questions", (string)null);
                });

            modelBuilder.Entity("QuizeService.Domain.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("QuizeService.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Platoon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_users_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QuizeService.Domain.Questions.MatchQuestion", b =>
                {
                    b.HasOne("QuizeService.Domain.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizeService.Domain.Test", null)
                        .WithMany("MatchQuestions")
                        .HasForeignKey("TestId1");

                    b.OwnsOne("QuizeService.Domain.Questions.Pairs", "Pairs", b1 =>
                        {
                            b1.Property<Guid>("MatchQuestionId")
                                .HasColumnType("uuid");

                            b1.Property<List<CorrectMatch>>("CorrectMatches")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("correct_matches");

                            b1.Property<List<Pair>>("LeftColumn")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("left_column");

                            b1.Property<List<Pair>>("RightColumn")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("right_column");

                            b1.HasKey("MatchQuestionId");

                            b1.ToTable("match_questions");

                            b1.WithOwner()
                                .HasForeignKey("MatchQuestionId");
                        });

                    b.Navigation("Pairs")
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("QuizeService.Domain.Questions.SingleChoiceQuestion", b =>
                {
                    b.HasOne("QuizeService.Domain.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizeService.Domain.Test", null)
                        .WithMany("SingleChoiceQuestions")
                        .HasForeignKey("TestId1");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("QuizeService.Domain.Questions.TextInputQuestion", b =>
                {
                    b.HasOne("QuizeService.Domain.Test", "Test")
                        .WithMany("TextInputQuestions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("QuizeService.Domain.Test", b =>
                {
                    b.Navigation("MatchQuestions");

                    b.Navigation("SingleChoiceQuestions");

                    b.Navigation("TextInputQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
